### ISSUE TITLE
Cannot submit Jterator pipeline in v0.4.0rc2

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#118]
In v0.4.0rc2, it is not possible to re-submit a workflow from the
Jterator pipeline stage (unless the Jterator pipeline was there from
the very start).  The web front-end just displays a "Failed" error
message; in the server-side logs, the following traceback appears:

    ERROR:tmserver.extensions.gc3pie:Error running job daemon command `redo`: could not resubmit task `62371`: Cannot redo 62371 from stage 3: only 3 stages in task list.
    Traceback (most recent call last):
      ...
      File "/home/tissuemaps/tmserver/tmserver/util.py", line 240, in wrapped
        return f(*args, **kwargs)
      File "/home/tissuemaps/tmserver/tmserver/api/workflow.py", line 222, in resubmit_workflow
        gc3pie.resubmit_task(workflow, index)
      File "/home/tissuemaps/tmserver/tmserver/extensions/gc3pie.py", line 362, in resubmit_task
        self._job_daemon_do('redo', str(task.persistent_id), str(index))
      File "/home/tissuemaps/tmserver/tmserver/extensions/gc3pie.py", line 170, in _job_daemon_do
        raise RuntimeError(msg)
    RuntimeError: Error running job daemon command `redo`: could not resubmit task `62371`: Cannot redo 62371 from stage 3: only 3 stages in task list.

Steps to reproduce:

1. Upload experiment;
2. Run ingestion workflow *without defining a Jterator pipeline*;
3. Upload a Jterator pipeline description;
4. Resubmit workflow from the Jterator part.

**Comment by riccardomurri** [comment]
I can confirm this is an issue of passing the updated task object from the server to the job daemon.

The fix seems to be on the job daemon side: it currently caches job objects for some time (while running and until memory does not need to be reclaimed), so we need to force the job daemon to unload and reload a task object from the DB upon resubmission.

**Comment by riccardomurri** [comment]
Fixed in https://github.com/TissueMAPS/TissueMAPS/commit/760f33341a75feb33a85f370d2bcb71ced6622e1
