### ISSUE TITLE
Downloading segmentation image of an empty site

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#128]
_From @jluethi on April 27, 2018 11:51_

If one tries to download the segmentation image of a site without this type of mapobjects, the download fails with the following error message:

`Traceback (most recent call last):
  File "/Users/Joel/.virtualenvs/tmclient_develop_align/bin/tm_client", line 11, in <module>
    load_entry_point('tmclient', 'console_scripts', 'tm_client')()
  File "/Users/Joel/TmClient/src/python/tmclient/api.py", line 293, in __main__
    client(args)
  File "/Users/Joel/TmClient/src/python/tmclient/api.py", line 249, in __call__
    method(**kwargs)
  File "/Users/Joel/TmClient/src/python/tmclient/api.py", line 1655, in download_segmentation_image_file
    tpoint, zplane, align
  File "/Users/Joel/TmClient/src/python/tmclient/api.py", line 1574, in _download_segmentation_image
    res.raise_for_status()
  File "/Users/Joel/.virtualenvs/tmclient_develop_align/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://172.23.47.46:80/api/experiments/dG1hcHM0/mapobject_types/dG1hcHMxMQ==/segmentations?well_pos_x=6&well_pos_y=5&align=True&plate_name=p1&tpoint=0&zplane=0&well_name=D10`

This is fine in interactive mode. But when using the client to download many images, getting an exception thrown here is very annoying. In the optimal case, the tmclient would return an all 0s image of the correct size (as no object is in there).

I can try, catch this afterwards, but that does not tell me how big the aligned image would be, something that tissuemaps could know. I looked at the _download_segmentation_image function in the tm_client API, but can't figure out how it would need to be adapted to do deal with this edge case.

_Copied from original issue: TissueMAPS/TmClient#30_

**Comment by riccardomurri** [comment]
_From @jluethi on May 23, 2018 12:54_

I made a workaround script for this case, but it needs some tweaking depending on your specific circumstances:
```
# Utility script to download all the segmentations from an experiment

import os
import json
from tmclient.api import TmClient
import shutil
import yaml
import png
import sys
import requests
import numpy as np
import cv2

# Variables to be set before using the script
host="172.23.XX.XX"
port = 80
experimentName="EXPERIMENT_NAME"
username="USERNAME"
password="XXXXXX"
mapobject="Cells"
output_path = '/data/active/PATH/TO/TARGET/'

will_align = True
cycle_index = 2  # Cycle index of first channel name (used as backup if there is no segmentation image for a site)

# Create tmclient instance
client_general = TmClient(host, port, username, password, experimentName)
# print json.dumps(mapobject_download,sort_keys=True, indent = 4, separators=(',', ': '))

# Get plate name
plateDownload = client_general.get_plates()
plate_name = plateDownload[0]['name']

# Get list of wells
wells = client_general.get_wells(plate_name = plate_name)

index = int(sys.argv[1])
well_id = wells[index]
# Initiate a new client instance per well, so that the token doesn't expire
client = TmClient(host, port, username, password, experimentName)
well = well_id.get('name')
print(well)
sites = client.get_sites(plate_name = plate_name, well_name = well)

# Loop through all sites, download segmentation
for site in sites:
    x = site.get('x')
    y = site.get('y')
    filename = os.path.join(output_path, experimentName +'Segmentation_' +
        mapobject +'_plate_' + plate_name + '_well_' + well +
        '_x' + str(x) + 'y' + str(y) + '.png')

    # This download fails with an error message if there is no mapobject in the specified site
    try:
        segmentation = client.download_segmentation_image(mapobject_type_name = mapobject,
            plate_name = plate_name, well_name = well, well_pos_y = y, well_pos_x = x,
            tpoint=0, zplane=0, align = will_align)

        ImageHeight = segmentation.shape[0]
        ImageWidth = segmentation.shape[1]

    except requests.exceptions.HTTPError:
        print('No objects of type ' + mapobject + ' in ' + well + '_x' +
            str(x) + '_y' + str(y) + '. Downloading an empty segmentation image instead.')
        # Because there is no actual object, one needs to figure out the dimensions of the segmentation image
        channel_names = client.get_channels()
        channelName = channel_names[0].get('name')
        response = client._download_channel_image(channel_name = channelName,
                        plate_name = plate_name, well_name = well,
                        well_pos_y = y, well_pos_x = x, cycle_index = cycle_index,
                        tpoint=0, zplane=0, correct = False, align = True)

        data = np.frombuffer(response.content, np.uint8)
        img = cv2.imdecode(data, cv2.IMREAD_UNCHANGED)
        ImageHeight = img.shape[0]
        ImageWidth = img.shape[1]

        segmentation = np.zeros([ImageHeight, ImageWidth])


    f = open(filename, 'wb')
    w = png.Writer(width = ImageWidth, height = ImageHeight, bitdepth = 16, greyscale=True)
    w.write(f, segmentation)
    f.close()
```
