### ISSUE TITLE
Issues with building docker images

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#136]
_From @jluethi on September 1, 2017 15:17_

With the current master of TmDeploy, the building of docker images in a virtualenv on my mac is failing. It gives the following error message. I don't know whether this is reproducible on science cloud, so I'm reporting it here for the meantime.

> ansible-container_1  | TASK [web-server : Update gulp proxy settings] *********************************
> Exception in thread Thread-15:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/Users/Joel/.virtualenvs/tmRelease030/lib/python2.7/site-packages/compose/cli/log_printer.py", line 197, in watch_events
>     for event in event_stream:
>   File "/Users/Joel/.virtualenvs/tmRelease030/lib/python2.7/site-packages/compose/project.py", line 343, in events
>     decode=True
>   File "/Users/Joel/.virtualenvs/tmRelease030/lib/python2.7/site-packages/docker/client.py", line 261, in _stream_helper
>     data = json.loads(data)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
>     raise ValueError(errmsg("Extra data", s, end, len(s)))
> ValueError: Extra data: line 2 column 1 - line 2 column 1042 (char 1044 - 2085)
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/Users/Joel/.virtualenvs/tmRelease030/lib/python2.7/site-packages/compose/cli/log_printer.py", line 197, in watch_events
>     for event in event_stream:
>   File "/Users/Joel/.virtualenvs/tmRelease030/lib/python2.7/site-packages/compose/project.py", line 343, in events
>     decode=True
>   File "/Users/Joel/.virtualenvs/tmRelease030/lib/python2.7/site-packages/docker/client.py", line 261, in _stream_helper
>     data = json.loads(data)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
>     raise ValueError(errmsg("Extra data", s, end, len(s)))
> ValueError: Extra data: line 2 column 1 - line 2 column 1042 (char 1044 - 2085)
> 
> 
> ansible-container_1  | changed: [web] => {"changed": true, "msg": "3 replacements made"}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Update gulp proxy settings] *********************************
> ansible-container_1  | changed: [web] => {"changed": true, "msg": "3 replacements made"}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Build client code for production deployment] ****************
> ansible-container_1  | changed: [web] => {"changed": true, "cmd": "gulp build --prod", "delta": "0:00:18.386906", "end": "2017-09-01 14:36:49.313103", "rc": 0, "start": "2017-09-01 14:36:30.926197", "stderr": "(node:16716) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.", "stdout": "PRODUCTION BUILD\n[14:36:32] Using gulpfile /var/www/tmui/src/gulpfile.js\n[14:36:32] Starting 'build'...\n[14:36:32] Starting 'clean'...\n[14:36:32] Finished 'build' after 8.14 ms\n[14:36:32] Finished 'clean' after 11 ms\n[14:36:32] Starting 'make-script'...\n[14:36:32] Starting 'make-style'...\n[14:36:34] Finished 'make-style' after 2.25 s\n[14:36:48] Finished 'make-script' after 16 s\n[14:36:48] Starting 'copy'...\n[14:36:49] Finished 'copy' after 196 ms", "stdout_lines": ["PRODUCTION BUILD", "[14:36:32] Using gulpfile /var/www/tmui/src/gulpfile.js", "[14:36:32] Starting 'build'...", "[14:36:32] Starting 'clean'...", "[14:36:32] Finished 'build' after 8.14 ms", "[14:36:32] Finished 'clean' after 11 ms", "[14:36:32] Starting 'make-script'...", "[14:36:32] Starting 'make-style'...", "[14:36:34] Finished 'make-style' after 2.25 s", "[14:36:48] Finished 'make-script' after 16 s", "[14:36:48] Starting 'copy'...", "[14:36:49] Finished 'copy' after 196 ms"], "warnings": []}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Set permissions for tmui/src directory] *********************
> ansible-container_1  | changed: [web] => {"changed": true, "gid": 1000, "group": "tissuemaps", "mode": "0700", "owner": "tissuemaps", "path": "/var/www/tmui/src", "size": 4096, "state": "directory", "uid": 1000}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Set permissions for tmui/src/build directory recursively] ***
> ansible-container_1  | changed: [web] => {"changed": true, "gid": 1000, "group": "tissuemaps", "mode": "0700", "owner": "tissuemaps", "path": "/var/www/tmui/src/build", "size": 4096, "state": "directory", "uid": 1000}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Set permissions for tmui/src/tasks directory recursively] ***
> ansible-container_1  | changed: [web] => {"changed": true, "gid": 1000, "group": "tissuemaps", "mode": "0700", "owner": "tissuemaps", "path": "/var/www/tmui/src/tasks", "size": 4096, "state": "directory", "uid": 1000}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Place NGINX configuration file] *****************************
> ansible-container_1  | changed: [web] => {"changed": true, "checksum": "d998f0844a7657b268f070967d96b4dab1bc4496", "dest": "/etc/nginx/nginx.conf", "gid": 1000, "group": "tissuemaps", "md5sum": "1e694ef3a9090c9acd2b569708f96ca1", "mode": "0700", "owner": "tissuemaps", "size": 1022, "src": "/root/.ansible/tmp/ansible-tmp-1504276611.2-140486323127687/source", "state": "file", "uid": 1000}
> ansible-container_1  | 
> ansible-container_1  | TASK [web-server : Place site specific NGINX conf.d (HTTP)] ********************
> ansible-container_1  | fatal: [web]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'uwsgi_timeout' is undefined"}
> ansible-container_1  | 	to retry, use: --limit @/ansible-container/ansible/main.retry
> ansible-container_1  | 
> ansible-container_1  | PLAY RECAP *********************************************************************
> ansible-container_1  | web                        : ok=26   changed=22   unreachable=0    failed=1   
> 

_Copied from original issue: TissueMAPS/TmDeploy#13_

**Comment by riccardomurri** [comment]
_From @hackermd on September 1, 2017 15:37_

I guess the problem was that the variable was only set on the `app` server, but it is required for the `web` service as well. Should be fixed with fefa8c69b5adf6f9da7dc19f1c9943185655a870
