### ISSUE TITLE
`tm_client microscope-file register` cannot register files from more than one directory

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#138]
Calling `tm_client microscope-file register directory1/ directory2/` results in files from `directory1/` being correctly registered, and then a server-side error happens and files in `directory2/` are never uploaded.

The server-side log shows this Python traceback:

```
Traceback (most recent call last):
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/util.py", line 137, in wrapped
    return f(*args, **kwargs)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/util.py", line 240, in wrapped
    return f(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/api/acquisition.py", line 394, in register
    os.symlink(path ,path_to_link.format(experiment.id,plate.id,acquisition.id) )
OSError: [Errno 17] File exists
```

**Comment by riccardomurri** [comment]
The current server-side `register()` code is implemented by symlinking the *root directory* passed to it as the acquisition directory.  Hence, all files to be registered must be in one and the same directory.

**Comment by riccardomurri** [comment]
The current server-side `register()` code is implemented by symlinking the *root directory* passed to it as the acquisition directory.  Hence, all files to be registered must be in one and the same directory.

**Comment by scottberry** [comment]
Also register does not seem to be working for experiments with multiple plates

server side:
```
[ 27556] 2018-09-28 09:03:14 | INFO     | tmserver.api.acquisition                 | register microscope files
[ 27556] 2018-09-28 09:03:14 | INFO     | tmserver.api.acquisition                 | path given by the client: /data/active/sberry/NascentRNA/20180920-NascentRNA-CompareCellTypes/TIFF/PLATE_02/CYCLE_01
[ 27556] 2018-09-28 09:03:37 | ERROR    | tmserver.appfactory                      | multiple results found: Multiple rows were found for one()
```

**Comment by scottberry** [comment]
OK, the issue may be from the old version. 
I am running v0.3.3 with some updates: 1647dd853aa62a1047c156855396f0e0507db9a5

**Comment by riccardomurri** [comment]
> I am running v0.3.3 with some updates: 1647dd8

Way too old. It's fixed in https://github.com/TissueMAPS/TissueMAPS/commit/8df8f14bf6c0d3d260a3f1e1038fb744d65e58fb which dates back to Sept. 16 (so it did not even make it into v0.4.1, it's still just "master")
