### ISSUE TITLE
tm_client feature-values upload - error

### ISSUE THREAD

**Issue by mimuelle** [TissueMAPS/TissueMAPS#175]
Upload of feature values for a single site failed with this error message:

``
2019-05-27 09:44:09 |  5126/MainThread  | ERROR   | Unterminated string starting at: line 3375 column 19 (char 89168) [[tmclient.api @ /home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py:298]]
``

This was the command I used:

``
tm_client feature-values -e 20190409_gw_screen_test_2 upload -o cells -p plate01 -w G09 -x 0 -y 0 -t 0 --filename /data/homes/mimuelle/GW_Screen/Optimization_data/single_site_new_feature.csv --index-col label
``

and these are the first 10 rows of the csv file I tried to upload:

label,EU_Area
12,50.3736669401148
13,1221.52635053361
14,597.941498086386
15,43.091896527083
16,829.229118387909
17,63.6636438582028
18,35.8670417530352
19,39.216332580463
20,81.831247765463
21,874.330506803392

**Comment by riccardomurri** [comment]
> `Unterminated string starting at: line 3375`

This looks like an error in the input data to me; what does line 3375 look like?

**Comment by riccardomurri** [comment]
cc @scottberry

**Comment by mimuelle** [comment]
there is no line 3375 since the file has only 166 lines

**Comment by riccardomurri** [comment]
Can you try this command pls:
```
tm_client -vvvvv feature-values -e 20190409_gw_screen_test_2 upload -o cells -p plate01 -w G09 -x 0 -y 0 -t 0 --filename /data/homes/mimuelle/GW_Screen/Optimization_data/single_site_new_feature.csv --index-col label
```

It should fail with the same error, but print a backtrace so we can see where the problem lies.

**Comment by mimuelle** [comment]
``Traceback (most recent call last):
  File "/usr/local/bin/tm_client", line 11, in <module>
    load_entry_point('tmclient', 'console_scripts', 'tm_client')()
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 295, in __main__
    client(args)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 251, in __call__
    method(**kwargs)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 2540, in upload_feature_value_file
    tpoint, data
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 2493, in _upload_feature_values
    mapobject_type_id = self._get_mapobject_type_id(mapobject_type_name)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 921, in _get_mapobject_type_id
    data = res.json()['data']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Unterminated string starting at: line 3375 column 19 (char 89168)``

**Comment by mimuelle** [comment]
``
Traceback (most recent call last):
  File "/usr/local/bin/tm_client", line 11, in <module>
    load_entry_point('tmclient', 'console_scripts', 'tm_client')()
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 295, in __main__
    client(args)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 251, in __call__
    method(**kwargs)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 2540, in upload_feature_value_file
    tpoint, data
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 2493, in _upload_feature_values
    mapobject_type_id = self._get_mapobject_type_id(mapobject_type_name)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 921, in _get_mapobject_type_id
    data = res.json()['data']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Unterminated string starting at: line 3375 column 19 (char 89168)
``

**Comment by mimuelle** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/tm_client", line 11, in <module>
    load_entry_point('tmclient', 'console_scripts', 'tm_client')()
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 295, in __main__
    client(args)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 251, in __call__
    method(**kwargs)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 2540, in upload_feature_value_file
    tpoint, data
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 2493, in _upload_feature_values
    mapobject_type_id = self._get_mapobject_type_id(mapobject_type_name)
  File "/home/tissuemaps/TissueMAPS/tmclient/src/python/tmclient/api.py", line 921, in _get_mapobject_type_id
    data = res.json()['data']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Unterminated string starting at: line 3375 column 19 (char 89168)

**Comment by riccardomurri** [comment]
This seems to be the error appearing in the server logs when I run the client command mentioned at the beginning of this thread:

```
DEBUG   | get channel layer tile: x=256, y=277, z=10, zplane=0, tpoint=0 [[tmserver.api.tile @ /.../TissueMAPS/tmserver/tmserver/api/tile.py:67]]
ERROR   | no result found: No row was found for one() [[tmserver.appfactory @ /.../TissueMAPS/tmserver/tmserver/appfactory.py:137]]
```

**Comment by riccardomurri** [comment]
This is the error appearing server-side:

```
KeyError : 'the label [1] is not in the [index]'
```

There's two issues here:

* The `try`/`except` block at `tmserver/api/feature.py` lines 245--253 is catching the wrong exception (`IndexError` instead of `KeyError`) -- this is fixed in commit 834e8de18

* TM is assuming that exactly one feature value is uploaded for each segmented object.  According to Micha, this is *not* the common case so we should get rid of this restriction and either skip missing objects or upload N/A feature values for them.

**Comment by scottberry** [comment]
It is indeed a common occurrence to not have feature values for all labels on a site. E.g. often border cells are immediately discarded and any features subsequently calculated would not exist for these cells. Ideally, NA would be used in the database when no label exists in the upload file.

However, I don't think that heatmaps are actually displayed for features that contain any missing values, so then these uploaded features would not be "view-able" in the viewer. In the long term this also need addressing (there is a related issue here: https://github.com/TissueMAPS/TissueMAPS/issues/63)

If it is not too difficult to change the heatmap behavior to allow missing values (should be displayed in grey or not at all), I would recommend this. Otherwise, in the short term these could be replaced with zeros (with a warning to the user).
