### ISSUE TITLE
Feature request: save images generated in jterator for viewing

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#34]
It would be great to be able to save images that are generated within a jterator pipeline for viewing. As an example, when working with 3D data, projection images could be saved, or in my case I am generating "volume images" (a 2D representation of cell height). It would be useful to be able to view these images in a similar manner to "channels" in the viewer. (In principle, any intermediate step in a jterator pipeline could be saved)

These could be referred to as "derived images" or "jterator intermediates" or something similar. However, one may also want to upload additional non-channel images such as probability maps generated by a pixel classifier to such a category, so perhaps a more generic name may be useful.

Being able to overlay 3D data and either 3D or 2D "derived images" in the viewer would be very useful.

As an additional request for combining 2D and 3D data, I think it should be a general assumption that all 2D features (e.g. cells segmented in 2D from a 3D dataset) should be visible across all z-planes. Or at least an option to allow this should be made available.

**Comment by scottberry** [comment]
Hi @riccardomurri ,

I have started working on saving images from jterator and have made reasonable progress so far. I implemented two new database tables for the image types and their file locations, and have added what I think is reasonable code for actually saving the images, their file locations in the database, and the files on the filesystem.

Trying to debug this code in jterator, I ran into more of a problem regarding tmui (probably because I have no idea what I am doing with javascript). 

At the moment there seems to be a mismatch regarding what the web interface generates as a pipeline description and what the backend is expecting. The error shown below is something you can observe in the uwsgi logs when hitting "save pipeline" for example.

After making changes to tmui, I have been re-building with ```gulp build --prod``` and then ```chown -R nginx:nginx ./build/``` since any edits here require sudo privileges. I then restarted the nginx and uwsgi servers. Is there something else I need to do to before running the UI code, for updates to take effect? What is grunt? Do I need to do something there?

As I understand it, the file from which pipeline descriptions are derived  is  ```TmLibrary/tmlib/workflow/jterator/description.py```, which I think I have edited sufficiently to add "image" outputs in addition to "object" outputs. This seems to be somewhat working, because a new experiment jterator pipeline file on the filesystem looks like:
```
---
input:
  channels: []
  objects: []
pipeline: []
output:
  images: []
  objects: []
```

However, when I try to make changes in the jterator UI and then save I hit an error. I tracked this down to ```flask.request.data``` [here](https://github.com/scottberry/TmServer/blob/develop/tmserver/jtui/api.py#L112) generating the following output:

```
experiment_id: dG1hcHM3
pipe:
  description:
    input:
      channels: []
      objects: []
    output:
      objects: []
    pipeline: []
handles: []
viewProps:
  selected: true
  open:
    project: false
    jobs: false
    pipeline: true
```

which does not contain "image" outputs. This then triggers the ultimate error shown below because an insufficient number of arguments are passed [here](https://github.com/scottberry/TmLibrary/blob/a17b73e9cce4297308c713d4b326eda607e919e1/tmlib/workflow/jterator/description.py#L268) 

If you have some ideas about what to try next that would be much appreciated. If you want to have a look around the server, please do, as I will not be working on this for the next week. You have the ssh keys and all repositories are currently on the new feature branch.

If you want to login to the frontend, I can send you the login details by email.

**My progress so far:**

tmlib:
https://github.com/TissueMAPS/TmLibrary/compare/develop...scottberry:feature/jterator-image-outputs?expand=1

tmui:
https://github.com/TissueMAPS/TmUI/compare/develop...scottberry:feature/jterator-image-outputs?expand=1

tmserver (just logging statements for debugging):
https://github.com/TissueMAPS/TmServer/compare/develop...scottberry:feature/jterator-image-outputs?expand=1

**Traceback for example error**

```
[ 12964] 2018-05-11 13:34:15 | INFO     | tmserver.jtui.api                        | save jterator project of experiment 7
[ 12964] 2018-05-11 13:34:15 | INFO     | tmserver.jtui.api                        | data[project] experiment_id: dG1hcHM3
pipe:
  description:
    input:
      channels: []
      objects: []
    output:
      objects: []
    pipeline: []
handles: []
viewProps:
  selected: true
  open:
    project: false
    jobs: false
    pipeline: true

[ 12964] 2018-05-11 13:34:15 | INFO     | tmserver.jtui.api                        | project {'pipe': {'description': {'input': {'channels': [], 'objects': []}, 'pipeline': [], 'output': {'objects': []}}}, 'handles': [], 'experiment_id': 'dG1hcHM3', 'viewProps': {'selected': True, 'open': {'project': False, 'pipeline': True, 'jobs': False}}}
Traceback (most recent call last):
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/util.py", line 135, in wrapped
    return f(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/util.py", line 240, in wrapped
    return f(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/jtui/api.py", line 116, in update_project
    pipeline_description = PipelineDescription(**project['pipe']['description'])
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/description.py", line 44, in __init__
    self.output = self._create_output_description(output)
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/description.py", line 72, in _create_output_description
    'description:\n%s' % str(err)
tmlib.errors.PipelineDescriptionError: Incorrect arguments provided for "output" section of pipeline description:
__init__() takes exactly 3 arguments (2 given)
```

**Comment by scottberry** [comment]
Hi @riccardomurri, it would be great if you could have a look at this during august. This will be extremely useful for my master's student project starting in September. If you want to take a look at the machine, I sent you login details for this by email on 11 May. Thanks.

**Comment by riccardomurri** [comment]
hi @scottberry sorry for the delay!  I'll try have a more in-depth look at this next week.  However, the initial message lists a lot of features that would be "nice to have": saving intermediate jterator outputs, but also uploading probability maps and viewing addiitional channels in the viewer... which of these features are needed for the sutdent project?  Having all of them ready by September might not be feasible.

**Comment by riccardomurri** [comment]
Regarding "saving intermediate Jterator results": would it be feasible to just have an additional module that does the saving?  I.e., within a Jterator pipeline, you would have a `save_channel_image` step which takes as input a single channel name and image file name, and saves the data into a file -- no output.  Would this work?

**Comment by scottberry** [comment]
Hi Riccardo,

Cool, thanks. The most important is to be able to save an image generated in a pipeline (normal 16-bit will be fine initially) and view that in the viewer.

Later we can add functionality within jterator to generate probability maps, etc.

Scott

**Comment by scottberry** [comment]
Yes, I think so, however Markus argued that jterator modules should not have any side effects (i.e. they should only modify objects in memory). That is why he suggested to add this as an additional 'output type' in the same way as objects are persisted.

**Comment by riccardomurri** [comment]
@scottberry I have ported your code to the new consolidated repository here: https://github.com/TissueMAPS/TissueMAPS/compare/master...riccardomurri:feature/jterator-image-outputs?expand=1

IOW, it's now in branch `feature/jterator-image-outputs` in my own TissueMAPS fork.

**Comment by riccardomurri** [comment]
> What is grunt? Do I need to do something there?

I'd say "no" -- `grunt` and `gulp` serve basically the same purpose (transforming/minifying JS code), but only `gulp` is used in TmDeploy's playbooks.

My guess is that Markus moved from Grunt to Gulp some time during the development of TM, but left the old build system around during the transition phase and then forgot to remove it.

**Comment by riccardomurri** [comment]
> a new experiment jterator pipeline file on the filesystem looks
> like: *[deletia]* However, when I try to make changes in the
> jterator UI and then save I hit an error.

I have checked the code path today and I can see no obvious errors;
will try with better logging next week.

However: I have seen cases (in unrelated issue reports) where TM fails
to update the workflow upon uploading a new YAML file; it seems that
the YAML files are only correctly parsed the first time around, and
subsequent changes may not be handled correctly.  Can you try again
with a new experiment, possibly after restarting the server, and using
the (new) correct Jterator YAML file with `output: { ..., images: []
}' from inception?

**Comment by riccardomurri** [comment]
Adding some more logging, this is where the (default) pipeline
description is read from and the actual content used for creating the
`PipelineDescription` object::

    [ 22950/uWSGIWorker2Core0] 2018-08-22 15:44:26 | DEBUG    | tmlib.readers                            | read from file: /storage/filesystem/experiment_2/workflow/jterator/pipeline.yaml
    [ 22950/uWSGIWorker2Core0] 2018-08-22 15:44:26 | DEBUG    | tmlib.workflow.jterator.project          | Content read from default pipeline: ordereddict([('input', ordereddic
    t([('channels', [ordereddict([('name', 'A04_C01'), ('correct', True)]), ordereddict([('name', 'A02_C02'), ('correct', True)]), ordereddict([('name', 'A01_C03'), ('correct',
     True)]), ordereddict([('name', 'A03_C04'), ('correct', True)]), ordereddict([('name', 'A04_C05'), ('correct', True)])]), ('objects', [])])), ('pipeline', [ordereddict([('a
    ctive', True), ('source', 'smooth.py'), ('handles', 'handles/smooth.handles.yaml')]), ordereddict([('active', True), ('source', 'threshold_otsu.py'), ('handles', 'handles/t
    hreshold_otsu.handles.yaml')]), ordereddict([('active', True), ('source', 'separate_clumps.py'), ('handles', 'handles/separate_clumps.handles.yaml')]), ordereddict([('activ
    e', True), ('source', 'filter.py'), ('handles', 'handles/filter.handles.yaml')]), ordereddict([('active', True), ('source', 'label.py'), ('handles', 'handles/label.handles.
    yaml')]), ordereddict([('active', True), ('source', 'register_objects.py'), ('handles', 'handles/register_objects.handles.yaml')]), ordereddict([('active', True), ('source'
    , 'smooth.py'), ('handles', 'handles/smooth_1.handles.yaml')]), ordereddict([('active', True), ('source', 'segment_secondary.py'), ('handles', 'handles/segment_secondary.ha
    ndles.yaml')]), ordereddict([('active', True), ('source', 'register_objects.py'), ('handles', 'handles/register_objects_1.handles.yaml')]), ordereddict([('active', True), (
    'source', 'clip.py'), ('handles', 'handles/clip.handles.yaml')]), ordereddict([('active', True), ('source', 'label.py'), ('handles', 'handles/label_1.handles.yaml')]), orde
    reddict([('active', True), ('source', 'register_objects.py'), ('handles', 'handles/register_objects_2.handles.yaml')]), ordereddict([('active', True), ('source', 'measure_m
    orphology.py'), ('handles', 'handles/measure_morphology.handles.yaml')]), ordereddict([('active', True), ('source', 'measure_morphology.py'), ('handles', 'handles/measure_m
    orphology_1.handles.yaml')]), ordereddict([('active', True), ('source', 'measure_intensity.py'), ('handles', 'handles/measure_intensity.handles.yaml')]), ordereddict([('act
    ive', True), ('source', 'measure_intensity.py'), ('handles', 'handles/measure_intensity_5.handles.yaml')]), ordereddict([('active', True), ('source', 'measure_intensity.py'
    ), ('handles', 'handles/measure_intensity_2.handles.yaml')]), ordereddict([('active', True), ('source', 'measure_intensity.py'), ('handles', 'handles/measure_intensity_3.ha
    ndles.yaml')]), ordereddict([('active', True), ('source', 'measure_intensity.py'), ('handles', 'handles/measure_intensity_4.handles.yaml')]), ordereddict([('active', True),
     ('source', 'measure_texture.py'), ('handles', 'handles/measure_texture.handles.yaml')]), ordereddict([('active', True), ('source', 'measure_texture.py'), ('handles', 'hand
    les/measure_texture_1.handles.yaml')])]), ('output', ordereddict([('objects', [])]))])

which pretty-prints as::

```json
{'input': {'channels': [{'correct': True, 'name': 'A04_C01'},
                        {'correct': True, 'name': 'A02_C02'},
                        {'correct': True, 'name': 'A01_C03'},
                        {'correct': True, 'name': 'A03_C04'},
                        {'correct': True, 'name': 'A04_C05'}],
           'objects': []},
 'output': {'objects': []},
 'pipeline': [{'active': True,
               'handles': 'handles/smooth.handles.yaml',
               'source': 'smooth.py'},
              {'active': True,
               'handles': 'handles/threshold_otsu.handles.yaml',
               'source': 'threshold_otsu.py'},
               # ...
              {'active': True,
               'handles': 'handles/measure_texture_1.handles.yaml',
               'source': 'measure_texture.py'}]}
```

So the `output.images` key is indeed missing.

**Manually editing `pipeline.yaml` server-side and adding the missing key makes the whole code work!**

**Comment by riccardomurri** [comment]
So the remaining question is: how does the initial (incorrect) `pipeline.yaml` get created?

**Comment by riccardomurri** [comment]
I tried deleting the `pipeline.yaml` file to force re-generating a new one; the server-side logs show that the default pipeline is created according to the the template in function `_create_pipe_file()` in lines 299--314 of file `tmlib/workflow/jterator/project.py`::

    [ 22949/uWSGIWorker1Core0] 2018-08-22 15:57:48 | INFO     | tmlib.workflow.jterator.project          | create pipeline descriptor file: /storage/filesystem/experiment_2/workflow/jterator/pipeline.yaml
    [ 22949/uWSGIWorker1Core0] 2018-08-22 15:57:48 | DEBUG    | tmlib.writers                            | write data to file: /storage/filesystem/experiment_2/workflow/jterator/pipeline.yaml
    [ 22949/uWSGIWorker1Core0] 2018-08-22 15:57:48 | DEBUG    | tmlib.workflow.jterator.project          | Creating default pipeline from u'/storage/filesystem/experiment_2/workflow/jterator/pipeline.yaml'
    [ 22949/uWSGIWorker1Core0] 2018-08-22 15:57:48 | DEBUG    | tmlib.readers                            | read from file: /storage/filesystem/experiment_2/workflow/jterator/pipeline.yaml
    [ 22949/uWSGIWorker1Core0] 2018-08-22 15:57:48 | DEBUG    | tmlib.workflow.jterator.project          | Content read from default pipeline: ordereddict([('input', ordereddict([('channels', []), ('objects', [])])), ('pipeline', []), ('output', ordereddict([('images', []), ('objects', [])]))])
    [pid: 22949|app: 0|req: 38/277] 172.23.79.118 () {38 vars in 712 bytes} [Wed Aug 22 15:57:48 2018] GET /jtui/experiments/2/project => generated 159 bytes in 16 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)

However, the YAML file returned to the client is missing the `output.images` key::

    # curl -i -X GET 'http://*.*.*.*/jtui/experiments/2/project' -H "Content-Type: application/json" -H "Authorization: JWT ey...-5z4" -d ''
    HTTP/1.1 200 OK
    ...
    Content-Type: application/json
    ...

    {
      "jtproject": "handles: []\npipe:\n  description:\n    input:\n      channels: []\n      objects: []\n    output:\n      objects: []\n    pipeline: []\n"
    }

So the response passed to the client must undergo another layer of deserialization/manipulation/serialization ...

**Comment by riccardomurri** [comment]
I think I have fixed the issue in commit f3cccc8d3 on my branch "feature/jterator-image-outputs". I'll try to test tomorrow.

**Comment by riccardomurri** [comment]
After commit f3cccc8 it works as expected and "Select images that should be saved:" appears in the pipeline definition page.

How do you want to proceed?  Shall I make a PR targeting your `feature/jterator-image-outputs` branch?  Or is the feature complete and I just merge into "master" and let it loose for people to try and report bugs?

**Comment by scottberry** [comment]
That’s great Riccardo, thanks. I’m not sure its complete yet but im happy to test. I haven’t forked the restructured TissueMAPS repo so you could commit to a feature branch on the main repo and I can fork that for testing/further development.

**Comment by riccardomurri** [comment]
@scottberry The working code is on my fork: https://github.com/riccardomurri/TissueMAPS/tree/feature/jterator-image-outputs  -- you can just check that out by adding it as a "remote" in your Git checkout.  To install, you will need to run `tm_deploy` from the joint repo as well (might work with the older versions but I haven't checked).
