### ISSUE TITLE
Support for non-equal z-stack dimensions between channels

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#50]
It is possible to acquire images with the Yokogawa CV7000 in which some channels are "z-stacks" and others are max projections or sum projections. In my case, this allows ~3-fold less data to be retained, copied, etc during acquisition. The final dataset ends up having single z-slices in some channels and multi z-slices in other channels.

I don't think this is currently supported in tissuemaps, and my test appears to fail during illumination correction (see below). This may also be a problem for pyramid creation?

I think this will be a common use-case, since people generally do not want to keep excess data they do not have to.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file api.py, line 88
2017-06-29 12:33:22 | WARNING  | tmlib.workflow.corilla.api               | no image files found for channel "wavelength-01"
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file api.py, line 88
2017-06-29 12:33:22 | WARNING  | tmlib.workflow.corilla.api               | no image files found for channel "wavelength-03"
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file api.py, line 88
2017-06-29 12:33:22 | WARNING  | tmlib.workflow.corilla.api               | no image files found for channel "wavelength-04"
```

**Comment by scottberry** [comment]
This is fixed in https://github.com/TissueMAPS/TissueMAPS/tree/v0.3.1, and pyramids can successfully be built
