### ISSUE TITLE
When jterator run job runs into timeout, the experiment gets stuck neither running nor terminated

### ISSUE THREAD

**Issue by jluethi** [TissueMAPS/TissueMAPS#55]
When jterator run job runs into timeout, the collect phase never starts, but also doesn't fail. Therefore, the step cannot be resubmitted with changed settings, because TissueMaps considers it still running.

![screen shot 2017-07-25 at 11 19 40](https://user-images.githubusercontent.com/18033446/28565116-8b9f12ce-712b-11e7-8c35-c9443959cbec.png)

**Comment by jluethi** [comment]
Those are the entries in the uwsgi log at the time when run job 1 hit the timelimit:
Brutally killing worker 4 (pid: 18224)...
Mon Jul 24 17:47:57 2017 - stopping gevent signals watchers for worker 4 (pid: 18224)...
Mon Jul 24 17:47:57 2017 - stopping gevent sockets watchers for worker 4 (pid: 18224)...
Mon Jul 24 17:47:57 2017 - main gevent watchers stopped for worker 4 (pid: 18224)...
Brutally killing worker 4 (pid: 18224)...
Mon Jul 24 17:47:57 2017 - stopping gevent signals watchers for worker 4 (pid: 18224)...
Mon Jul 24 17:47:57 2017 - stopping gevent sockets watchers for worker 4 (pid: 18224)...
Mon Jul 24 17:47:57 2017 - main gevent watchers stopped for worker 4 (pid: 18224)...
goodbye to the gevent Hub on worker 4 (pid: 18224)
goodbye to the gevent Hub on worker 1 (pid: 18221)
2017-07-24 17:47:57 | ERROR    | gc3.gc3libs                              | Could not kill job '330'. It refers to non-existent local process 20547.
2017-07-24 17:47:57 | ERROR    | gc3.gc3libs                              | Ignoring error in updating state of task '330': InvalidValue: Could not open wrapper file `/var/tmp/gc3libs.zTIraG/.gc3pie_shellcmd/resource_usage.txt` for task `330`: 'shellcmd_user_time'
Traceback (most recent call last):
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 1470, in progress
   self._core.update_job_state(task)
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 424, in update_job_state
   **extra_args)
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 462, in __update_application
   raise ex
InvalidValue: Could not open wrapper file `/var/tmp/gc3libs.zTIraG/.gc3pie_shellcmd/resource_usage.txt` for task `330`: 'shellcmd_user_time'
2017-07-24 17:47:57 | ERROR    | gc3.gc3libs                              | Ignoring error in updating state of task '331': InvalidValue: Could not open wrapper file `/var/tmp/gc3libs.8Jy9wV/.gc3pie_shellcmd/resource_usage.txt` for task `331`: 'shellcmd_user_time'
Traceback (most recent call last):
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 1470, in progress
   self._core.update_job_state(task)
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 424, in update_job_state
   **extra_args)
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 462, in __update_application
   raise ex
InvalidValue: Could not open wrapper file `/var/tmp/gc3libs.8Jy9wV/.gc3pie_shellcmd/resource_usage.txt` for task `331`: 'shellcmd_user_time'
2017-07-24 17:47:57 | ERROR    | gc3.gc3libs                              | Ignoring error in updating state of task '332': InvalidValue: Could not open wrapper file `/var/tmp/gc3libs.raaqev/.gc3pie_shellcmd/resource_usage.txt` for task `332`: 'shellcmd_user_time'
Traceback (most recent call last):
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 1470, in progress
   self._core.update_job_state(task)
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 424, in update_job_state
   **extra_args)
 File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 462, in __update_application
   raise ex
InvalidValue: Could not open wrapper file `/var/tmp/gc3libs.raaqev/.gc3pie_shellcmd/resource_usage.txt` for task `332`: 'shellcmd_user_time'
Brutally killing worker 3 (pid: 18223)...
Mon Jul 24 17:47:57 2017 - stopping gevent signals watchers for worker 3 (pid: 18223)...
Mon Jul 24 17:47:57 2017 - stopping gevent sockets watchers for worker 3 (pid: 18223)...
Mon Jul 24 17:47:57 2017 - main gevent watchers stopped for worker 3 (pid: 18223)...
Brutally killing worker 3 (pid: 18223)...
Mon Jul 24 17:47:57 2017 - stopping gevent signals watchers for worker 3 (pid: 18223)...
Mon Jul 24 17:47:57 2017 - stopping gevent sockets watchers for worker 3 (pid: 18223)...
Mon Jul 24 17:47:57 2017 - main gevent watchers stopped for worker 3 (pid: 18223)...
goodbye to the gevent Hub on worker 3 (pid: 18223)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.

Maybe @riccardomurri you have an idea?

**Comment by jluethi** [comment]
See https://github.com/TissueMAPS/TissueMAPS/issues/110 for details
