### ISSUE TITLE
TmClient 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by scottberry** [TissueMAPS/TissueMAPS#56]
client:
https://github.com/TissueMAPS/TmClient/commit/92e55a6575dcde35e5ef098d292afa94e9ae1988

host:
https://github.com/TissueMAPS/TmServer/commit/579a6b1458ca325b5c992d56b0c540b751fae626
https://github.com/TissueMAPS/TmLibrary/commit/b2296de5d9d94aecdfbd3c5ac7af60c82f4b2f8e

Upload failing for large dataset ~57000 images. after uploading ~30000 images, there is an error causing failure to complete the upload. Resubmission of upload using the same command gives the following error:

```
ubuntu@scott-tm-deploy:~$ tm_client -vvvv -H 172.23.15.27 -u scott -p 123456 microscope-file -e 20170608-Kim2-EU-PCNA-Beads upload -p plate01 -a acq01 --directory ~/pelkmans-sc-storage/20170608-Kim2-EU-PCNA-Beads/TIFF_VOLUME/
2017-07-27 07:48:32 | DEBUG    | tmclient.base                            | use HTTP protocol
2017-07-27 07:48:32 | DEBUG    | tmclient.base                            | login in as user "scott"
2017-07-27 07:48:32 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/auth
2017-07-27 07:48:33 | DEBUG    | tmclient.api                             | call method "upload_microscope_files"
2017-07-27 07:48:33 | INFO     | tmclient.api                             | upload microscope files for experiment "20170608-Kim2-EU-PCNA-Beads", plate "plate01" and acquisition "acq01"
2017-07-27 07:48:33 | DEBUG    | tmclient.api                             | get acquisition ID for experiment "20170608-Kim2-EU-PCNA-Beads", plate "plate01" and acquisition "acq01"
2017-07-27 07:48:33 | DEBUG    | tmclient.api                             | get ID for experiment "20170608-Kim2-EU-PCNA-Beads"
2017-07-27 07:48:33 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/api/experiments?name=20170608-Kim2-EU-PCNA-Beads
2017-07-27 07:48:33 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/api/experiments/dG1hcHM1/acquisitions?plate_name=plate01&name=acq01
2017-07-27 07:48:33 | DEBUG    | tmclient.api                             | register files for upload
2017-07-27 07:48:33 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/api/experiments/dG1hcHM1/acquisitions/dG1hcHMx/upload/register
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tm_client", line 9, in <module>
    load_entry_point('tmclient', 'console_scripts', 'tm_client')()
  File "/home/ubuntu/TmClient/src/python/tmclient/api.py", line 189, in __main__
    client(args)
  File "/home/ubuntu/TmClient/src/python/tmclient/api.py", line 164, in __call__
    method(**kwargs)
  File "/home/ubuntu/TmClient/src/python/tmclient/api.py", line 1057, in upload_microscope_files
    acquisition_id, filenames
  File "/home/ubuntu/TmClient/src/python/tmclient/api.py", line 1075, in _register_files_for_upload
    res.raise_for_status()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: http://172.23.15.27:80/api/experiments/dG1hcHM1/acquisitions/dG1hcHMx/upload/register
```

**Comment by scottberry** [comment]
Restarting host server did not resolve the issue

**Comment by scottberry** [comment]
Corresponding uwsgi log:
`2017-07-27 07:48:33 | INFO     | tmserver.api.experiment                  | get experiments
2017-07-27 07:48:33 | INFO     | tmserver.api.experiment                  | filter experiments for name "20170608-Kim2-EU-PCNA-Beads"
[pid: 5136|app: 0|req: 15995/72492] 172.23.11.24 () {38 vars in 735 bytes} [Thu Jul 27 07:48:33 2017] GET /api/experiments?name=20170608-Kim2-EU-PCNA-Beads => generated 151 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 96)
2017-07-27 07:48:33 | INFO     | tmserver.api.acquisition                 | get acquistions for experiment 5
[pid: 5135|app: 0|req: 13223/72493] 172.23.11.24 () {38 vars in 773 bytes} [Thu Jul 27 07:48:33 2017] GET /api/experiments/dG1hcHM1/acquisitions?plate_name=plate01&name=acq01 => generated 165 bytes in 34 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 97)
2017-07-27 07:48:34 | INFO     | tmserver.api.acquisition                 | register microscope files for upload
2017-07-27 07:50:45 | INFO     | tmserver.api.acquisition                 | registered 26461 files
Thu Jul 27 07:50:45 2017 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during POST /api/experiments/dG1hcHM1/acquisitions/dG1hcHMx/upload/register (172.23.11.24)
IOError: write error
[pid: 5138|app: 0|req: 23983/72494] 172.23.11.24 () {42 vars in 855 bytes} [Thu Jul 27 07:44:46 2017] POST /api/experiments/dG1hcHM1/acquisitions/dG1hcHMx/upload/register => generated 0 bytes in 359584 msecs (HTTP/1.1 200) 2 headers in 0 bytes (94 switches on core 97)
[pid: 5137|app: 0|req: 19294/72495] 172.23.11.24 () {40 vars in 520 bytes} [Thu Jul 27 07:52:21 2017] POST /auth => generated 208 bytes in 350 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
`

**Comment by scottberry** [comment]
@riccardomurri your bug-fix resolved this error, however upload will not go to completion. I don't think any new files are uploaded. Client side, the last lines before tm_client stopped were:

```
2017-07-27 16:19:13 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/api/experiments/dG1hcHMz/acquisitions/dG1hcHMx/microscope-file
2017-07-27 16:19:14 | INFO     | tmclient.api                             | upload file: 20170622-Kim2-NuclearFISH-beads-plate_C04_T0001F032L01A03Z17C03.tif
2017-07-27 16:19:14 | DEBUG    | tmclient.api                             | upload file: /home/ubuntu/pelkmans-sc-storage/20170615-Kim2-Nucl-FISH/TIFF_VOLUME/20170622-Kim2-NuclearFISH-beads-plate_C04_T0001F032L01A03Z17C03.tif
2017-07-27 16:19:14 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/api/experiments/dG1hcHMz/acquisitions/dG1hcHMx/microscope-file
2017-07-27 16:19:15 | INFO     | tmclient.api                             | upload file: 20170622-Kim2-NuclearFISH-beads-plate_D04_T0001F039L01A03Z36C03.tif
2017-07-27 16:19:15 | DEBUG    | tmclient.api                             | upload file: /home/ubuntu/pelkmans-sc-storage/20170615-Kim2-Nucl-FISH/TIFF_VOLUME/20170622-Kim2-NuclearFISH-beads-plate_D04_T0001F039L01A03Z36C03.tif
2017-07-27 16:19:15 | DEBUG    | tmclient.base                            | url: http://172.23.15.27:80/api/experiments/dG1hcHMz/acquisitions/dG1hcHMx/microscope-file
```

On the server there was not much noteworthy in the uwsgi log
```
2017-07-27 16:19:15 | INFO     | tmserver.api.acquisition                 | acquisition already complete
[pid: 22755|app: 0|req: 5313/13895] 172.23.11.24 () {42 vars in 949 bytes} [Thu Jul 27 16:19:15 2017] POST /api/experiments/dG1hcHMz/acquisitions/dG1hcHMx/microscope-file => generated 40 bytes in 113 msecs (HTTP/1.1 200) 2 headers in 71 bytes (50 switches on core 99)
[pid: 22754|app: 0|req: 2733/13896] 172.23.11.24 () {40 vars in 520 bytes} [Thu Jul 27 16:24:01 2017] POST /auth => generated 208 bytes in 351 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 98)
2017-07-27 16:24:01 | INFO     | tmserver.api.experiment                  | get experiments
```

**Comment by hackermd** [comment]
@scottberry @riccardomurri What's the status here? Can this be closed?

**Comment by scottberry** [comment]
No this is still an issue.

I have hit this again recently by simultaneously uploading and processing. Bernhard also had similar problems on the most recent release when uploading his multiplexing data.

@riccardo, I don't think anyone has tried to reproduce this and debug yet?

**Comment by hackermd** [comment]
My guess is that this is also related to uWSGI timeouts, see #66
