### ISSUE TITLE
Available modules not showing up in web-UI 

### ISSUE THREAD

**Issue by sparkvilla** [TissueMAPS/TissueMAPS#72]
I noticed that in TM version0.3.3 at the level of **Image Analysis Pipeline** the **available modules** are not showing up. The inspect front-end command gives:

    Error: e.jtmodules is undefined
 

I guess this has to do with the **jtmodules** merged with **jtlibrary**. This has high priority since people cannot build their pipeline and not process their images. How can we fix this?

**Comment by jluethi** [comment]
I haven't dealt with this before, but I assume it's a TMUI setting that would need to be corrected. @hackermd Do you know what needs to be changed?
My assumption is that it's the lines 20 & 21 in TmUI/src/app/src/jtui/components/module/moduleService.js:
`var modulelist = data.jtmodules.modules;
  var registration = data.jtmodules.registration;`

Though I don't know where the "data" gets these parameters. @sparkvilla maybe you can trace them?

**Comment by jluethi** [comment]
Thanks to the help of @riccardomurri , I think we can narrow down the problem to this commit https://github.com/TissueMAPS/TmLibrary/commit/16993c808ab79e4ed2d27d70b7ca5916958e809e and the changes to this file: tmlib/workflow/jterator/project.py.

If we look at the error trace in uwsgi when TissuesMaps fails to load the modules, we see this:
[  8869] 2017-09-12 08:38:28 | INFO     | tmserver.jtui.api                        | get list of available jterator modules
Traceback (most recent call last):
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
[pid: 8871|app: 0|req: 12689/45925] 89.206.118.120 () {48 vars in 1078 bytes} [Tue Sep 12 08:38:28 2017] POST /jtui/experiments/dG1hcHMy/jobs/output => generated 19 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
    return fn(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/jtui/api.py", line 139, in get_available_modules
    return jsonify(jtmodules=modules.to_dict())
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/project.py", line 593, in to_dict
    attrs['modules'] = self.handles
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/project.py", line 539, in handles
    for name in self.module_names:
  File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/project.py", line 484, in module_names
    for f in self.module_files
  **File "/home/tissuemaps/tmlibrary/tmlib/workflow/jterator/project.py", line 471, in module_files**
    **r = re.compile(search_strings.values())**
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 237, in _compile
    p, loc = _cache[cachekey]
TypeError: unhashable type: 'list'

So it seems that this new way of doing a regex to find the modules is failing.

**Comment by riccardomurri** [comment]
I think this error is fixed by pull request https://github.com/TissueMAPS/TmLibrary/pull/40 -- @sparkvilla can you please try it?

(Then maybe there are more issues which were masked by that traceback.)

**Comment by sparkvilla** [comment]
@riccardomurri I have merged it. I will try it out. Keep you posted

**Comment by riccardomurri** [comment]
Maybe it would have been better to swap the steps and try it out before merging ;-)

**Comment by sparkvilla** [comment]
@riccardomurri That solved it! Thanks

**Comment by riccardomurri** [comment]
All is well what ends well! :-)
