### ISSUE TITLE
jterator error: Multiple rows were found for one_or_none()

### ISSUE THREAD

**Issue by sparkvilla** [TissueMAPS/TissueMAPS#74]
A user launched a iterator run with simple thresholding (otsu) as a first step -- and she got an "Multiple rows were found for one_or_none()" error. It repeatedly appears when she tries to access the jterator pipeline (in the GUI), or when she tries to resume a job.

On the server side, here the python traceback:

    [ 14307] 2017-09-18 00:08:21 | ERROR    | gc3.gc3libs                              | Got ValueError executing     delayed call remove(*(<tmlib.workflow.workflow.Workflow object at 0x7fab3cc65390>,), **{}):     list.remove(x): x not in list
    Traceback (most recent call last):
      File "/home/tissuemaps/tmserver/tmserver/extensions/gc3pie/engine.py", line 245, in _perform
        fn(*args, **kwargs)
      File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 1331, in remove
        queue.remove(task)
    ValueError: list.remove(x): x not in list

**Comment by riccardomurri** [comment]
The traceback points to an error with GC3Pie, but that does not match the reported error message "Multiple rows were found for one_or_none()" which comes from the DB processing layer of TM.

The GC3Pie error is quite likely harmless and has little or nothing to do with the actual problem: it just means that GC3Pie was not able to kill a job.  I would suggest lowering the uWSGI processes to 1 -- this would slow down the web interface, but should make the GC3Pie error disappear, and then you should be able to better see the root cause of the problem in the logs.

**Comment by sparkvilla** [comment]
Tried to lower the process number and restart the server but the problem is still there. Here is a more verbose log,  the `one_or_none()` appears at line 132479 and down. I anyway added your pub key to the vm (IP=172.23.166.81) so that you can look at the all log.

    132432 [pid: 14309|app: 0|req: 2356/7726] 89.206.116.182 () {48 vars in 1064 bytes} [Wed Sep 13   11:11:26 2017] POST /api/experiments/dG1hcHMz/workflow/re       submit => generated 46 bytes in  347 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
    132433 [ 14308] 2017-09-13 11:11:28 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 3
    132434 [pid: 14308|app: 0|req: 1500/7727] 89.206.116.182 () {42 vars in 912 bytes} [Wed Sep 13 11:11:28 2017] GET /api/experiments/dG1hcHMz/workflow/stat       us => generated 4123 bytes in 52 msecs (HTTP/1.1 200) 2 headers in 73 bytes (4 switches on core 99)
    132435 [ 14309] 2017-09-13 11:11:28 | INFO     | tmserver.api.plate                       | get plates for experiment 3
    132436 [ 14308] 2017-09-13 11:11:28 | INFO     | tmserver.api.workflow                    | get status of jobs for workflow step "illuminati" of experime       nt 3
    132437 [pid: 14309|app: 0|req: 2357/7728] 89.206.116.182 () {42 vars in 894 bytes} [Wed Sep 13 11:11:28 2017] GET /api/experiments/dG1hcHMz/plates => gen       erated 340 bytes in 25 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 99)
    132438 [pid: 14308|app: 0|req: 1501/7729] 89.206.116.182 () {42 vars in 993 bytes} [Wed Sep 13 11:11:28 2017] GET /api/experiments/dG1hcHMz/workflow/jobs       ?step_name=illuminati&index=0&batch_size=50 => generated 17 bytes in 15 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 99)
    132439 [ 14310] 2017-09-13 11:11:29 | INFO     | tmserver.api.workflow                    | get status of jobs for workflow step "illuminati" of experime       nt 3
    132440 [pid: 14310|app: 0|req: 2577/7730] 89.206.116.182 () {42 vars in 997 bytes} [Wed Sep 13 11:11:29 2017] GET /api/experiments/dG1hcHMz/workflow/jobs       ?step_name=illuminati&index=-50&batch_size=50 => generated 17 bytes in 7 msecs (HTTP/1.1 200) 2 headers in 71 bytes (4 switches on core 94)
    132441 [ 14309] 2017-09-13 11:11:31 | ERROR    | gc3.gc3libs                              | Got ValueError executing delayed call remove(*(<tmlib.workflo       w.workflow.Workflow object at 0x7fab3d2e4750>,), **{}): list.remove(x): x not in list
    132442 Traceback (most recent call last):
    132443   File "/home/tissuemaps/tmserver/tmserver/extensions/gc3pie/engine.py", line 245, in _perform
    132444     fn(*args, **kwargs)
    132445   File "/home/tissuemaps/.local/lib/python2.7/site-packages/gc3libs/core.py", line 1331, in remove
    132446     queue.remove(task)
    132447 ValueError: list.remove(x): x not in list
    132448 [ 14308] 2017-09-13 11:11:38 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 3
    132449 [pid: 14308|app: 0|req: 1502/7731] 89.206.116.182 () {42 vars in 912 bytes} [Wed Sep 13 11:11:38 2017] GET /api/experiments/dG1hcHMz/workflow/stat       us => generated 6444 bytes in 71 msecs (HTTP/1.1 200) 2 headers in 73 bytes (4 switches on core 99)
    132450 [ 14310] 2017-09-13 11:11:38 | INFO     | tmserver.api.plate                       | get plates for experiment 3
    132451 [ 14307] 2017-09-13 11:11:38 | INFO     | tmserver.api.workflow                    | get status of jobs for workflow step "illuminati" of experime       nt 3
    132452 [pid: 14310|app: 0|req: 2578/7732] 89.206.116.182 () {42 vars in 894 bytes} [Wed Sep 13 11:11:38 2017] GET /api/experiments/dG1hcHMz/plates => gen       erated 340 bytes in 27 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 94)
    132453 [ 14307] 2017-09-13 11:11:38 | ERROR    | tmserver.appfactory                      | multiple results found: Multiple rows were found for one_or_n       one()
    132454 [pid: 14307|app: 0|req: 1296/7733] 89.206.116.182 () {42 vars in 993 bytes} [Wed Sep 13 11:11:38 2017] GET /api/experiments/dG1hcHMz/workflow/jobs       ?step_name=illuminati&index=0&batch_size=50 => generated 143 bytes in 15 msecs (HTTP/1.1 409) 2 headers in 78 bytes (4 switches on core 97)
    132455 [ 14310] 2017-09-13 11:11:48 | INFO     | tmserver.api.workflow                    | get workflow status for experiment 3
    132456 [pid: 14310|app: 0|req: 2579/7734] 89.206.116.182 () {42 vars in 912 bytes} [Wed Sep 13 11:11:48 2017] GET /api/experiments/dG1hcHMz/workflow/stat       us => generated 6531 bytes in 62 msecs (HTTP/1.1 200) 2 headers in 73 bytes (4 switches on core 94)
    132457 [ 14310] 2017-09-13 11:11:48 | INFO     | tmserver.api.plate                       | get plates for experiment 3
    132458 [pid: 14310|app: 0|req: 2580/7735] 89.206.116.182 () {42 vars in 894 bytes} [Wed Sep 13 11:11:48 2017] GET /api/experiments/dG1hcHMz/plates => gen       erated 340 bytes in 24 msecs (HTTP/1.1 200) 2 headers in 72 bytes (4 switches on core 94)
    132459 [ 14310] 2017-09-13 11:11:48 | INFO     | tmserver.api.workflow                    | get status of jobs for workflow step "illuminati" of experime       nt 3
    132460 [ 14310] 2017-09-13 11:11:48 | ERROR    | tmserver.appfactory                      | multiple results found: Multiple rows were found for one_or_n       one()
    132461 [pid: 14310|app: 0|req: 2581/7736] 89.206.116.182 () {42 vars in 993 bytes} [Wed Sep 13 11:11:48 2017] GET /api/experiments/dG1hcHMz/workflow/jobs       ?step_name=illuminati&index=0&batch_size=50 => generated 143 bytes in 13 msecs (HTTP/1.1 409) 2 headers in 78 bytes (4 switches on core 94)

**Comment by riccardomurri** [comment]
Well, at least now we know the source of the problem::

    tmserver.appfactory | multiple results found: Multiple rows were found for one_or_none()

so the error is logged by module `tmserver.appfactory`; the exception might be raised some layers deeper, while running whatever function logs the message "get status of jobs for workflow step "illuminati" of experiment 3"
