### ISSUE TITLE
TmServer: uploading empty `pipeline.yaml` file results in HTTP 502 error later on

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#96]
The current server-side API allows uploads of empty `pipeline.yaml`
files.  These are internally mapped to Python `None` objects, which
make subsequent run/download/whatever Jterator operations fail with a
traceback like this::

```
Traceback (most recent call last):
  ...
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/util.py", line 135, in wrapped
    return f(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/util.py", line 240, in wrapped
    return f(*args, **kwargs)
  File "/home/tissuemaps/tmserver/tmserver/api/workflow.py", line 703, in update_project
    pipeline_description = PipelineDescription(**pipeline)
TypeError: type object argument after ** must be a mapping, not NoneType
```

**Comment by riccardomurri** [comment]
Actually I'm not sure if the traceback comes from the upload operation or the later process/download request.  It's still possible that TmServer errors out during upload but still removes / updates the pipeline with a `None` object. In that case, we have two problems: *(1)* that the error is not propagated to the clients, *(2)* that the internal state is updated in a way that makes later processing invalid.

**Comment by riccardomurri** [comment]
Hmm, it's look like we're indeed in the case where *upload* is
failing, while still updating state in an invalid way::

```
[ 23651] 2017-11-03 10:21:51 | INFO     | tmserver.api.workflow                    | update jterator project of experiment 1
Traceback (most recent call last):
    ...
  File "/home/tissuemaps/tmserver/tmserver/api/workflow.py", line 703, in update_project
    pipeline_description = PipelineDescription(**pipeline)
TypeError: type object argument after ** must be a mapping, not NoneType
[pid: 23651|app: 0|req: 7929/25709] ... PUT /api/experiments/dG1hcHMx/workflow/jtproject => generated 0 bytes in 10 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 99)
```

The logs clearly show that the error happened during `HTTP PUT /api/experiments/dG1hcHMx/workflow/jtproject`.
