### ISSUE TITLE
TmServer: metadata download return empty file upon DB error

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TissueMAPS#97]
Reported by Raffa: after re-running a (modified) pipeline, the metadata download apparently succeeds but the CSV file is empty (consists of just the header).  In the server logs we could find::

```
[pid: 1466|app: 0|req: 65/172] 172.23.143.140 () {38 vars in 745 bytes} [Wed Nov  8 18:41:32 2017] GET /api/experiments/dG1hcHM1/m                            
apobject_types?name=Cells => generated 104511 bytes in 48 msecs (HTTP/1.1 200) 2 headers in 75 bytes (4 switches on core 99)                                  
Traceback (most recent call last):                                                                                                                            
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 704, in __next__                                                          
    return self._next()                                                                                                                                       
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded                                                  
    for item in iterable:                                                                                                                                     
  File "/home/tissuemaps/tmserver/tmserver/api/feature.py", line 607, in generate_feature_matrix                                                              
    session, mapobject_ids, ref_mapobject_type.id, ref_id                                                                                                     
  File "/home/tissuemaps/tmserver/tmserver/api/mapobject.py", line 175, in _get_border_mapobjects_at_ref_position                                             
    tm.Mapobject.mapobject_type_id == ref_type_id                                                                                                             
  File "/home/tissuemaps/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2817, in one                                                       
    "Multiple rows were found for one()")                                                                                                                     
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()                                                                                   
[pid: 1466|app: 0|req: 66/173] 172.23.143.140 () {38 vars in 823 bytes} [Wed Nov  8 18:41:32 2017] GET /api/experiments/dG1hcHM1/m                            
apobject_types/dG1hcHM3/metadata?well_name=D07&plate_name=plate1 => generated 165 bytes in 58 msecs (HTTP/1.1 200) 2 headers in 14                            
2 bytes (3 switches on core 99)                                                                                                                               
```

**Comment by riccardomurri** [comment]
There is not enough info ATM to understand where the problem is coming from.  As a first step, add better logging/error capture so that we can report what failed and where (what query, on which database, etc.)

**Comment by riccardomurri** [comment]
Adding some debugging code server-side we can see that TM expects the following query to return one and only one result, whereas we have 47 distinct ones!
```
tissuemaps=> SELECT count(distinct mapobject_segmentations.geom_polygon) AS mapobject_segmentations_geom_polygon FROM mapobject_segmentations JOIN mapobjects ON mapobjects.partition_key = mapobject_segmentations.partition_key AND mapobjects.id = mapobject_segmentations.mapobject_id  WHERE mapobjects.partition_key = 1 AND mapobjects.mapobject_type_id = 6;
 mapobject_segmentations_geom_polygon
--------------------------------------
                                   47
```
Further poking around the DB shows plausible results for the number of "map objects" and "map object segmentations":
```
tissuemaps=> select count(mapobjects.id) from mapobjects;
 count  
--------
 261718
(1 row)

tissuemaps=> select count(mapobject_segmentations.mapobject_id) from mapobject_segmentations;
 count  
--------
 261688
(1 row)

tissuemaps=> select count(distinct mapobject_segmentations.mapobject_id) from mapobject_segmentations where mapobject_segmentations.partition_key = 1;
 count
-------
    97
(1 row)

tissuemaps=> select count(distinct mapobjects.id) from mapobjects where mapobjects.partition_key = 1;
 count
-------
    97
(1 row)
```
(Note: fixing the partition_key is necessary for the DISTINCT key to work -- apparently Citus does not allow SELECT ... DISTINCT over sharded DBs.)

**Comment by riccardomurri** [comment]
For the record, this is the debugging code used to display the SQL query::
```diff
diff --git a/tmserver/api/mapobject.py b/tmserver/api/mapobject.py
index 5bb9cf1..21a56c0 100644
--- a/tmserver/api/mapobject.py
+++ b/tmserver/api/mapobject.py
@@ -166,15 +166,22 @@
 
 def _get_border_mapobjects_at_ref_position(session, mapobject_ids,
         ref_type_id, ref_id):
-    ref_segmentation = session.query(
+    logger.debug(
+        "Querying polygons with `mapobject_type_id==%s`"
+        " and `partition_key==%s`", ref_type_id, ref_id)
+    q = session.query(
             tm.MapobjectSegmentation.geom_polygon
         ).\
         join(tm.Mapobject).\
         filter(
             tm.Mapobject.partition_key == ref_id,
             tm.Mapobject.mapobject_type_id == ref_type_id
-        ).\
-        one()
+        )
+    # evaluating `q.*.statement` might be costly,
+    # so only do it if running in non-optimized mode
+    if __debug__:
+        logger.debug("Running SQL query `%s` ...", q.with_labels().statement)
+    ref_segmentation = q.one()
 
     return session.query(tm.MapobjectSegmentation.mapobject_id).\
         filter(
```

**Comment by riccardomurri** [comment]
My guess is that the root of the problem is in some repeated Jterator pipeline which inserted multiple copies of the data.  The only place in the TM server code where the `geom_polygon` column is actually *written* to is this part of function `add_segmentations()` (file `tmserver/api/mapobject.py` lines 548--567):

```python
    with tm.utils.ExperimentSession(experiment_id, False) as session:
        segmentations = list()
        for label, polygon in image.extract_polygons(y_offset, x_offset):
            mapobject = tm.Mapobject(site_id, mapobject_type_id)
            if label in existing_segmentations_map:
                # A parent mapobject with the same label may already exist,
                # because it got already created for another zplane/tpoint.
                # The segmentation for the given zplane/tpoint must not yet
                # exist, however. This will lead to an error upon insertion.
                mapobject.id = existing_segmentations_map[label]
            else:
                session.add(mapobject)
                session.flush()
            s = tm.MapobjectSegmentation(
                partition_key=site_id, mapobject_id=mapobject.id,
                geom_polygon=polygon, geom_centroid=polygon.centroid,
                segmentation_layer_id=segmentation_layer_id, label=label
            )
            segmentations.append(s)
        session.bulk_ingest(segmentations)
```

Note that the comment warns that *"The segmentation for the given zplane/tpoint must not yet exist, however. This will lead to an error upon insertion." -- but then errors upon insertion `session.bulk_ingest()` are not checked, which can lead to re-doing part of the same insertion(s) over and over again if the some of them failed...

**Comment by riccardomurri** [comment]
Actually, it is also possible that the API code in `generate_feature_matrix` is doing the wrong thing -- it is calling `_get_border_mapobjects_at_ref_position()` which makes sense when the reference mapobject is a "site" but not when it's another kind of "map object"...

**Comment by riccardomurri** [comment]
Actually, mapobject type 6  is "Nuclei" but it's registered as a "Site" type::

```sql
tissuemaps=> select * from experiment_5.mapobject_types limit 10;
 id |  name  | ref_type | experiment_id 
----+--------+----------+---------------
  6 | Nuclei | Site     |             5
  7 | Cells  | Site     |             5
  8 | Plates | Plate    |             5
  9 | Sites  | Site     |             5
 10 | Wells  | Well     |             5
(5 rows)
```

I'm very confused now -- why would the code extract border mapobjects on Nuclei? Why are "Nuclei" a kind of "Site"?

**Comment by hackermd** [comment]
> I'm very confused now -- why would the code extract border mapobjects on Nuclei? Why are "Nuclei" a kind of "Site"?

They are not a kind of site, but distributed by `site_id` and can be referenced relative to a site.
